config/routes.rb
Mybeers::Application.routes.draw do

  resources :users
  resources :beers do
    resources :reviews, :only => [:create, :update], :modulo => :beers
  end

  resource :user_sessions, :only => [:create, :new, :destroy]

  root :to => "home#index"
end

app/models/beer.rb
#encoding: utf-8

class Beer < ActiveRecord::Base

  scope :most_recent, order('created_at DESC')

  belongs_to :user
  has_many :reviews

  validates :name, :presence => true
  validates :style, :presence => true

  def stars
    reviews.stars
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  POINTS = (1..5).to_a

  belongs_to :user
  belongs_to :beer, :counter_cache => true

  validates_uniqueness_of :user_id, :scope => :beer_id
  validates_inclusion_of  :point, :in => POINTS
  validates :point, :user_id, :beer_id, :presence => true

  def self.stars
    (average(:point) || 0).round
  end

  def self.review_points
    Review::POINTS.last
  end

end

app/models/user.rb
#encoding: utf-8

class User < ActiveRecord::Base

  has_many :beers
  has_many :reviews

  scope   :most_recent, order('create_at DESC')

  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true, :format => {:with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/}

  validates_confirmation_of :password

  has_secure_password

  def self.authenticate (email, password)
    self.find_by_email(email).try(:authenticate, password)
  end
end

app/models/user_session.rb
class UserSession

  include ActiveModel::Model

  attr_accessor :email, :password

  validates :email, :presence => true
  validates :password, :presence => true

  def initialize(session, attribute={})
    @session = session
    @email = attribute[:email]
    @password = attribute[:password]
  end

  def authenticate
    user = User.authenticate(@email, @password)

    if user.present?
      store(user)
    else
      errors.add(:base, :invalid_login)
      false
    end
  end

  def store(user)
    @session[:user_id] = user.id
  end

  def persisted?
    false
  end

  def current_user
    User.find(@session[:user_id])
  end

  def user_signed_in?
    @session[:user_id].present?
  end

  def destroy
    @session[:user_id] = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  delegate :current_user, :user_signed_in?, :to => :user_session
  helper_method :current_user, :user_signed_in?

  def user_session
    UserSession.new(session)
  end

  def require_authentication
    unless user_signed_in?
      redirect_to new_user_sessions_path, :alert => t('flash.alert.needs_login')
    end
  end

  def require_no_authentication
    redirect_to root_path if user_signed_in?
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  before_filter :require_authentication, :only => [:new, :edit, :create, :update, :destroy]

  def index
    @beers = Beer.most_recent.order(:style, :name)
  end

  def show

    @beer = Beer.find(params[:id])
    if user_signed_in?
      @user_review = @beer.reviews.find_or_initialize_by_user_id(current_user.id)
    end
  end

  def new
    @beer = current_user.beers.build
  end

  def edit
    @beer = current_user.beers.find(params[:id])
  end

  def destroy
    @beer = current_user.beers.find(params[:id])
    @beer.destroy

    redirect_to(beers_url, :notice => t('flash.notice.destroy'))
  end

  def create
    @beer = current_user.beers.build beer_params

    if(@beer.save)
      redirect_to @beer, :notice => t('flash.notice.beer_created')
    else
      render :action =>"new"
    end
  end

  def update
    @beer = current_user.beers.find(params[:id])

    if @beer.update_attributes(beer_params)
      redirect_to @beer, :notice => t('flash.notice.updated')
    else
      render :action => "edit"
    end
  end

  private
    def beer_params
      params.require(:beer).permit(:name, :style, :description, :brewery, :location, :color, :alcohol, :foam, :aroma)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :require_authentication

  def create

    review = beer.reviews.find_or_initialize_by_user_id(current_user.id)

    review.update_attributes!(params_review)

    head :ok
  end

  def update
    create
  end

private

  def beer
    @beer ||= Beer.find(params[:beer_id])
  end

  def params_review
    params.require(:review).permit(:beer_id, :point)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    @session = UserSession.new(session)
  end

  def create
    @session = UserSession.new(session, session_params)

    if(@session.authenticate)
      redirect_to root_path, :notice => t('flash.notice.signed_in')
    else
      render :new
    end

  end

  def destroy
    user_session.destroy
    redirect_to root_path, :notice => t('flash.notice.signed_out')
  end

  private
  def session_params
    params.require(:user_session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController

  before_filter :can_change, :only => [:edit, :update, :show]
  before_filter :require_authentication, :only => [:destroy]

  def index
    @users = User.order(:name)
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to(users_url, :notice => "Usuário #{@user.name} Criado Com Sucesso !!!")
    else
      render :action => "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to(users_url, :notice => "Usuário #{@user.name} Autalizado Com Sucesso !!!")
    else
      render :action => "edit"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to(users_url, :notice => "Usuário Excluído")
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def can_change
    unless user_signed_in? && current_user == user
      redirect_to user_path(params[:id])
    end
  end

  def user
    @user ||= User.find(params[:id])
  end
end

app/helpers/Beers_Helper.rb
module BeersHelper

  def belongs_to_user(beer)
    user_signed_in? && beer.user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if(model.errors.has_key? attribute)
      content_tag :div, model.errors[attribute].first, :class => 'error_message'
    end
  end

  def show_errors_tag(model)

    if(model.errors.any?)
      html = "<div id='error_explanation'>"
      html += "<h2>#{model.errors.count} #{t('errors.error').pluralize} #{t('errors.message')} </h2>"
      html += "<ul>"

      model.errors.full_messages.each do |err|
        html += "<li>#{err}</li>"
      end

      html += "</ul>"
      html += "</div>"
      html.html_safe
    end
  end
end

app/views/beers/_beer.html.erb
  <article class="beer">
    <h2> <%= link_to beer.name, beer %> </h2>

    <span class="created">
      <%= t'.owner_html', :owner => beer.user.name, :when => l(beer.created_at, :format => :short) %>
    </span>

    <p>
      <%= t '.stats', :average => beer.reviews.stars, :max => beer.reviews.review_points, :count => beer.reviews.size %>
    </p>

    <p>
      <% beer.stars.times do %>
        <span class="star filled_star"></span>
      <% end %>

      <% (beer.reviews.review_points - beer.stars).times do %>
        <span class="star empty_star"></span>
      <% end %>

      <%= t '.stars', :count => beer.reviews_count %>
    </p>

    <p>
      <span class="style">
        <%= beer.style%>
      </span>
    </p>
    <p><%= beer.description %></p>
    <% if belongs_to_user beer %>
      <ul>
        <li>
          <%= link_to t('links.edit'), edit_beer_path(beer) %> |
          <%= link_to t('links.destroy'), beer, method: :delete, data: { confirm: t('links.question_destroy') } %>
        </li>
      </ul>
    <% end %>

  </article>

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>

  <%= show_errors_tag @beer %>

  <fieldset>
    <div class="actions">
      <table>
        <tbody>
          <tr>
            <TD><%=f.label :name %></TD>
            <TD>
              <%=f.text_field :name %>
              <%= error_tag @beer, :name %>
            </TD>
          </tr>
          <tr>
            <TD><%=f.label :style %></TD>
            <TD>
              <%=f.text_field :style %>
              <%= error_tag @beer, :style %>
            </TD>
          </tr>
          <tr>
            <TD><%=f.label :brewery %></TD>
            <TD><%=f.text_field :brewery %></TD>
          </tr>
          <tr>
            <TD><%=f.label :location %></TD>
            <TD><%=f.text_field :location %></TD>
          </tr>
          <tr>
            <TD><%=f.label :color %></TD>
            <TD><%=f.text_field :color %></TD>
          </tr>
          <tr>
            <TD><%=f.label :alcohol %></TD>
            <TD><%=f.text_field :alcohol %></TD>
          </tr>
          <tr>
            <TD><%=f.label :foam %></TD>
            <TD><%=f.text_field :foam %></TD>
          </tr>
          <tr>
            <TD><%=f.label :aroma %></TD>
            <TD><%=f.text_field :aroma %></TD>
          </tr>
          <tr>
            <TD><%=f.label :description %></TD>
            <TD><%=f.text_area :description %></TD>
          </tr>
        </tbody>
      </table>

      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/beers/_review.html.erb
<section class="review">
  <% if user_signed_in? %>

    <%= form_for [review.beer, review], :remote => true do |f| %>

      <% Review::POINTS.each do |point| %>

        <%= f.radio_button :point, point %>

        <%= f.label :point, point, :value => point do %>
          <i class="icon-star"></i>
        <% end %>
      <% end %>

      <%= f.submit %>
    <% end %>

  <% else %>
    <span class="login_required">
      <%= t('.login_to_review')%>
    </span>
  <% end %>

</section>

app/views/beers/edit.html.erb
<h1><%= t('.title')%></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @beer %> |
<%= link_to t('links.back'), beers_path %>

app/views/beers/index.html.erb
<h1><%= t('.title')%></h1>

<%= render @beers %>

<%= link_to t('.new'), new_beer_path %>

app/views/beers/new.html.erb
<h1><%= t '.title'%></h1>

<%= render 'form' %>

<%= link_to t('links.back'), beers_path %>

app/views/beers/show.html.erb
<h3><%=@beer.name %></h3>

  <%= render :partial => 'review', :object => @user_review %>

  <fieldset>
    <div class="actions">
      <table>
        <tbody>
          <tr>
            <TD><%=@beer.style %></TD>
          </tr>
          <tr>
            <TD><%=@beer.brewery %></TD>
          </tr>
          <tr>
            <TD><%=@beer.location %></TD>
          </tr>
          <tr>
            <TD><%=@beer.color %></TD>
          </tr>
          <tr>
            <TD><%=@beer.alcohol %></TD>
          </tr>
          <tr>
            <TD><%=@beer.foam %></TD>
          </tr>
          <tr>
            <TD><%=@beer.aroma %></TD>
          </tr>
          <tr>
            <TD>
              <%= text_area_tag :description, @beer.description, :size=> "80x6", :disabled => true%>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </fieldset>

<%= link_to t('links.edit'), edit_beer_path(@beer) %> |
<%= link_to t('links.back'), beers_path %>

app/views/home/index.html.erb
<h1>Bender - MyBeer</h1>

<p>
  <ul>
    <li><%= link_to "Usuarios", users_path %></li>
    <li><%= link_to "Cervejas", beers_path %></li>
  </ul>
</p>

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.beers'), beers_path %> </li>
    <li><%= link_to t('layout.new_beer'), new_beer_path %> </li>
    <li><%= link_to t('layout.my_profile'), user_path(current_user) %></li>
    <li><%= link_to t('layout.signout'), user_sessions_path, :method => :delete %></li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.beers'), beers_path %> </li>
    <li><%= link_to t('layout.signup'), new_user_path %> </li>
    <li><%= link_to t('layout.signin'), new_user_sessions_path %> </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mybeers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="content">

  <header>
    <div id="header-wrap">
      <h1><%= link_to "ByBeer", root_path %> </h1>

      <% if user_signed_in? %>
        <%= render 'layouts/user_navbar' %>
      <% else %>
        <%= render 'layouts/visitor_navbar' %>
      <% end %>
    </div>
  </header>

  <% if notice.present? %>
    <p id="notice"><%= notice %> </p>
  <% end %>
  <% if alert.present? %>
    <p id="alert"><%= alert %> </p>
  <% end %>
  <p><%= link_to "Home", root_path%></p>
  <%= yield %>
</div>

</body>
</html>

app/views/user_sessions/new.html.erb
<h1><%= t'.title' %></h1>
<%= show_errors_tag @session %>

<%= form_for @session do |f|  %>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= error_tag @session, :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %> <%= error_tag @session, :password %>
  </p>
  <p>
    <%= f.submit :value => t('layout.signin') %>
  </p>
<% end %>

<p><%= link_to t('.sign_up'), new_user_path %> </p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= show_errors_tag @user %>

  <fieldset>
    <div class="actions">

      <table>
        <tbody>
          <tr>
            <TD><%=f.label :name %></TD>
            <TD>
              <%=f.text_field :name %>
              <%= error_tag @user, :name %>
            </TD>
          </tr>
          <tr>
            <TD><%=f.label :email %></TD>
            <TD>
              <%=f.text_field :email %>
              <%= error_tag @user, :email %>
            </TD>
          </tr>
          <tr>
            <TD><%=f.label :password %></TD>
            <TD>
              <%=f.password_field :password %>
              <%= error_tag @user, :password %>
            </TD>
          </tr>
          <tr>
            <TD><%=f.label :password_confirmation %></TD>
            <TD>
              <%=f.password_field :password_confirmation %>
              <%= error_tag @user, :password_confirmation %>
            </TD>
          </tr>
        </tbody>
      </table>

      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1><%= t('.title')%></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @user %> |
<%= link_to t('links.back'), users_path %>

app/views/users/index.html.erb
<h1><%= t('.title')%></h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to t('links.show'), user %></td>
        <td><%= link_to t('links.edit'), edit_user_path(user) %></td>
        <td><%= link_to t('links.destroy'), user, method: :delete, data: { confirm: t('links.question_destroy') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_user_path %>

app/views/users/new.html.erb
<h1><%= t '.title' %> </h1>

<%= render 'form' %>

<%= link_to t('links.back'), users_path %>

app/views/users/show.html.erb
<h3><%=@user.name %></h3>
<h3><%=@user.email %></h3>

<%= link_to t('links.edit'), edit_user_path(@user) %> |
<%= link_to t('links.back'), users_path %>